CREATE   TABLE   riskreport_firedanger
    (
        riskFileNo 	CHAR(22) NOT NULL	COMMENT  '风控档案编号',
        fireProofSeparate 	VARCHAR(1)	COMMENT  '防火分隔',
        buildStructure 	VARCHAR(1)	COMMENT  '建筑结构',
        buildUseYear	 VARCHAR(1)	COMMENT  '建筑使用年限',
        buildOwnerShipNature	 VARCHAR(1)	COMMENT  '建筑所有权性质',
        fireLoadDensity 	VARCHAR(1)	COMMENT  '火灾荷载密度（建筑物内所容纳可燃物容积占比）',
        mainMaterialBurnNature 	VARCHAR(1)	COMMENT  '主要生产或仓储材料燃烧性质',
        explodeProductEnviron	 VARCHAR(1)	COMMENT  '有无爆炸生产环境',
        dangerProcessPart 	VARCHAR(20)	COMMENT  '危险工艺部位（可多选）',
        chargePosition 	VARCHAR(1)	COMMENT  '作业车充电位置',
        lineYear 	VARCHAR(1)	COMMENT  '电气线路投入使用年限',
        storageAreaLight 	VARCHAR(1)	COMMENT  '仓储区域灯具',
        storageSituation	 VARCHAR(1)	COMMENT  '仓储存放情况',
        lineDistance 	VARCHAR(1)	COMMENT  '电气线路或用电设备与可燃物周边间距',
        proIrrelevantDevice	VARCHAR(1)	COMMENT  '生产和仓储场所有其他无关电器设备',
        fireFacility 	VARCHAR(20)	COMMENT  '消防设施',
        indoorHydrantSystem	 VARCHAR(1)	COMMENT  '室内消火栓系统',
        outdoorHydrantSystem 	VARCHAR(1)	COMMENT  '室外消火栓系统',
        fireExtinguisher 	VARCHAR(1)	COMMENT  '灭火器',
        fireEquipmentPassage	 VARCHAR(1)	COMMENT  '消防器材通道',
        autoExtinguishSystem	 VARCHAR(20)	COMMENT  '自动灭火系统',
        autoAlarmSystemStatus 	VARCHAR(1)	COMMENT  '自动报警系统状态',
        autoAlarmSystemWatch 	VARCHAR(1)	COMMENT  '自动报警系统监',
        fireWaterSupply	 VARCHAR(20)	COMMENT  '消防水源供应',
        electricLineProtect 	VARCHAR(1)	COMMENT  '电气线路保护',
        fireSeparation	 VARCHAR(1) COMMENT  '防火间距',
        bodyBetweenBuild 	VARCHAR(1)	COMMENT  '建筑物间存在物体',
        surroundEnvironment 	VARCHAR(1)	COMMENT  '厂区周边环境',
        establishFireSafety 	VARCHAR(1)	COMMENT  '企业是否建立消防安全组织架构',
        configureFireFighter	 VARCHAR(1)	COMMENT  '是否配置专兼职消防人员',
        fireCheckHappen	 VARCHAR(1)	COMMENT  '防火巡查、检查制度及落实情况',
        hotFireApproval 	VARCHAR(1)	COMMENT  '动火审批制度和落实情况',
        fireDrill	 VARCHAR(1)	COMMENT  '开展消防演练情况',
        fireTrain	 VARCHAR(1)	COMMENT  '定期对员工的消防培训',
        fireMaintenance	 VARCHAR(1)	COMMENT  '消防设施维护保养',
        noSmokeManage 	VARCHAR(1)	COMMENT  '禁烟管理情况',
        fireControlDuty 	VARCHAR(1)	COMMENT  '消防控制室值班制度',
        rectificateSuggest	 VARCHAR(1)	COMMENT  '一年内是否收到相关消防安全管理部门风险警示或整改建议函',
        insertTimeForHis  DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT  '插入时间',
        operateTimeForHis  DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT  '修改时间',   
        PRIMARY KEY (riskFileNo) 
    )ENGINE=InnoDB DEFAULT CHARSET=utf8;
   
    
   drop table if exists  riskreport_main;
   CREATE TABLE
    riskreport_main
    (
        riskFileNo CHAR(22) NOT NULL COMMENT  '风险档案编号',
        classCode CHAR(2) NOT NULL COMMENT  '险类代码',
        riskCode CHAR(3) NOT NULL COMMENT  '产品代码',
        comCode CHAR(8) NOT NULL COMMENT  '归属机构',
        stockRate DECIMAL(5,2) COMMENT '存货比例',
        riskModel VARCHAR(3) COMMENT '风控报告模板 ',
        insuredType VARCHAR(1) COMMENT '被保险人类型',
        insuredCode VARCHAR(30) COMMENT '被保险人代码 ',
        insuredName VARCHAR(120) COMMENT '被保险人姓名/企业名称',
        addressProvince VARCHAR(30) COMMENT '保险财产地址(省)',
        addressCity VARCHAR(40) COMMENT '保险财产地址(市)',
        addressCounty VARCHAR(60) COMMENT '保险财产地址(区或县)',
        addressDetail VARCHAR(255) COMMENT '保险财产地址(详细)',
        postCode VARCHAR(6) COMMENT ' 邮政编码',
        businessSource VARCHAR(6) COMMENT '国民经济行业代码',
        businessClass VARCHAR(2) COMMENT '行业类型代码',
        unitNature VARCHAR(1) COMMENT '被保险人/企业性质 ',
        underwriteStatus VARCHAR(1) COMMENT '以往承保情况 ',
        operatorCode VARCHAR(10) COMMENT '操作人员代码 ',
        operatorCode_uni VARCHAR(10) COMMENT ' 操作人员集团统一工号',
        historyLoseFlag VARCHAR(1) COMMENT ' 三年内历史赔付损失记录',
        sumAmount DECIMAL(14,4) COMMENT '总保险金额',
        undwrtSubmitDate DATE COMMENT  '提交核保时间 ',
        underwriteFlag VARCHAR(1) COMMENT '核保标志 ',
        underwriteDate DATE COMMENT  '核保通过时间',
        underwriteCode VARCHAR(10) COMMENT '核保人员姓名',
        underwriteName VARCHAR(120) COMMENT '核保人员姓名',
        explorecomCode VARCHAR(8) COMMENT '查勘机构',
        explorer VARCHAR(10) COMMENT '查勘人',
        explorer_uni VARCHAR(10) COMMENT '查勘人集团统一工号',
        exploreDate DATE COMMENT  '查勘日期',
        madeDate DATETIME COMMENT  '制作日期',
        exploreType VARCHAR(1) COMMENT ' 查勘类别:1 初勘,2 复勘',
        lastriskFileNo VARCHAR(22) COMMENT '初勘风控报告编号',
        mobileFlag CHAR(1) NOT NULL COMMENT  '请求端标志 0-web 1-Android 2-IOS',
        archivesNo VARCHAR(22) COMMENT '照片编号',
        addRisk VARCHAR(15) COMMENT  '投保附加险情况 A 扩展盗窃、抢劫责任   B 扩展供应中断责任  C 扩展露天堆放责任',
        customerExplain TEXT COMMENT  '需要替换',
        onceAccidentLosest DECIMAL(14,2) COMMENT '单次事故可能最大损失',
        riskUnitNumber INTEGER COMMENT  ' 危险单位数量',
        riskUnitExplain TEXT COMMENT  '危险单位划分说明 ',
        loseRate DECIMAL(5,2) COMMENT '损失率',
        highlightRisk TEXT COMMENT  '突出风险',
        score DECIMAL(5,2) COMMENT '综合得分',
        supplementAppraisal TEXT COMMENT  '现场评估补充说明 *or***风险隐患说明',
        riskSuggest VARCHAR(1) COMMENT '需要替换',
        othSuggest TEXT COMMENT  '风控建议 ',
        addMessage TEXT COMMENT  '补充说明 * or **防灾防损建议',
        utiWeightId INTEGER COMMENT  '所使用的权重表id',
        executionId VARCHAR(50) COMMENT '所使用的流程实例id',
        repulseSugggest text  COMMENT '拒绝建议',
        pointx_2000 DECIMAL(20,15) COMMENT '2000坐标系经度',
        pointy_2000 DECIMAL(20,15) COMMENT '2000坐标系纬度',
        pointx_02 DECIMAL(20,15) COMMENT '02坐标系经度',
        pointy_02 DECIMAL(20,15) COMMENT '02坐标系纬度',
        valuation VARCHAR(1) COMMENT '风险评估等级',
        proposalNo CHAR(22) COMMENT '投保单号 ',
        policyNo CHAR(22) COMMENT '保单号',
         insertTimeForHis DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT  ' 插入时间',
        operateTimeForHis DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT  '更新时间',
        PRIMARY KEY (riskFileNo) 
    )ENGINE=InnoDB DEFAULT CHARSET=utf8;  
    
 
drop table if exists riskreport_assess;
CREATE TABLE
    riskreport_assess
    (
        riskFileNo CHAR(22) NOT NULL  COMMENT  '风险档案编号',
        fireDanger DECIMAL(5,2)  COMMENT  '火灾',
        waterDanger DECIMAL(5,2)  COMMENT  '水灾',
        windDanger DECIMAL(5,2)  COMMENT  '风灾',
        thunderDanger DECIMAL(5,2)  COMMENT  '雷雨灾害',
        snowDanger DECIMAL(5,2)  COMMENT  '雪灾',
        theftDanger DECIMAL(5,2)  COMMENT  '盗抢灾害',
        earthQuakeDanger DECIMAL(5,2)  COMMENT  '地震灾害',
        geologyDanger DECIMAL(5,2)  COMMENT  '地质灾害',
        inserttimeforhis DATETIME default NOW(),
        operatetimeforhis DATETIME default  NOW(),
        PRIMARY KEY (riskFileNo)
    )ENGINE=InnoDB DEFAULT CHARSET=utf8;
    
  