-----安全工厂主表
drop table if exists RiskReport_SafeFactoryMain;
		comment on column RiskReport_SafeFactoryMain.riskfileno is '风控报告编号';
        comment on column RiskReport_SafeFactoryMain.classcode CHARACTER VARYING(2),
        comment on column RiskReport_SafeFactoryMain.riskcode CHARACTER VARYING(3),
        comment on column RiskReport_SafeFactoryMain.comcode CHARACTER VARYING(8),
        comment on column RiskReport_SafeFactoryMain.riskmodel CHARACTER VARYING(3),
        comment on column RiskReport_SafeFactoryMain.insuredtype CHARACTER VARYING(1),
        comment on column RiskReport_SafeFactoryMain.insuredcode CHARACTER VARYING(30),
        comment on column RiskReport_SafeFactoryMain.insuredname CHARACTER VARYING(120),
        comment on column RiskReport_SafeFactoryMain.postcode CHARACTER VARYING(6),
        comment on column RiskReport_SafeFactoryMain.businesssource CHARACTER VARYING(6),
        comment on column RiskReport_SafeFactoryMain.businessclass CHARACTER VARYING(2),
        comment on column RiskReport_SafeFactoryMain.unitnature CHARACTER VARYING(1),
        comment on column RiskReport_SafeFactoryMain.underwritestatus CHARACTER VARYING(1),
        comment on column RiskReport_SafeFactoryMain.operatorcode CHARACTER VARYING(10),
        comment on column RiskReport_SafeFactoryMain.operatorcodeuni CHARACTER VARYING(10),
        comment on column RiskReport_SafeFactoryMain.sumamount NUMERIC(14,4),
        comment on column RiskReport_SafeFactoryMain.undwrtsubmitdate DATE,
        comment on column RiskReport_SafeFactoryMain.underwriteflag CHARACTER VARYING(1),
        comment on column RiskReport_SafeFactoryMain.underwritedate DATE,
        comment on column RiskReport_SafeFactoryMain.underwritecode CHARACTER VARYING(10),
        comment on column RiskReport_SafeFactoryMain.underwritename CHARACTER VARYING(120),
        comment on column RiskReport_SafeFactoryMain.explorecomcode CHARACTER VARYING(8),
        comment on column RiskReport_SafeFactoryMain.explorer CHARACTER VARYING(10),
        comment on column RiskReport_SafeFactoryMain.exploreruni CHARACTER VARYING(10),
        comment on column RiskReport_SafeFactoryMain.exploredate DATE,
        comment on column RiskReport_SafeFactoryMain.madedate DATE,
        comment on column RiskReport_SafeFactoryMain.exploretype CHARACTER VARYING(1),
        comment on column RiskReport_SafeFactoryMain.lastriskfileno CHARACTER VARYING(22),
        comment on column RiskReport_SafeFactoryMain.mobileflag CHARACTER VARYING(1),
        comment on column RiskReport_SafeFactoryMain.archivesno CHARACTER VARYING(22),
        comment on column RiskReport_SafeFactoryMain.addrisk CHARACTER VARYING(15),
        comment on column RiskReport_SafeFactoryMain.customerexplain CHARACTER VARYING(4000),
        comment on column RiskReport_SafeFactoryMain.onceaccidentlosest NUMERIC(14,2),
        comment on column RiskReport_SafeFactoryMain.riskunitnumber INTEGER,
        comment on column RiskReport_SafeFactoryMain.riskunitexplain CHARACTER VARYING(4000),
        comment on column RiskReport_SafeFactoryMain.loserate NUMERIC(5,2),
        comment on column RiskReport_SafeFactoryMain.highlightrisk CHARACTER VARYING(4000),
        comment on column RiskReport_SafeFactoryMain.score NUMERIC(5,2),
        comment on column RiskReport_SafeFactoryMain.supplementappraisal CHARACTER VARYING(4000),
        comment on column RiskReport_SafeFactoryMain.risksuggest CHARACTER VARYING(1),
        comment on column RiskReport_SafeFactoryMain.othsuggest CHARACTER VARYING(4000),
        comment on column RiskReport_SafeFactoryMain.addmessage CHARACTER VARYING(4000),
        comment on column RiskReport_SafeFactoryMain.utiweightid INTEGER,
        comment on column RiskReport_SafeFactoryMain.executionid CHARACTER VARYING(50),
        comment on column RiskReport_SafeFactoryMain.repulsesugggest CHARACTER VARYING(1000),
        comment on column RiskReport_SafeFactoryMain.valuation CHARACTER VARYING(1),
        comment on column RiskReport_SafeFactoryMain.proposalno CHARACTER VARYING(22),
        comment on column RiskReport_SafeFactoryMain.policyno CHARACTER VARYING(22),
        comment on column RiskReport_SafeFactoryMain.insert_time_for_his TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        comment on column RiskReport_SafeFactoryMain.operate_time_for_his TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    
    